// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CareRegimen struct {
	ID      string `json:"id"`
	Waterml int    `json:"waterml"`
	Waterhr int    `json:"waterhr"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Member struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	CreatedOn string `json:"createdOn"`
}

type NewCareRegimen struct {
	Waterml int `json:"waterml"`
	Waterhr int `json:"waterhr"`
}

type NewMember struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewNurseryAddition struct {
	PlantID       string `json:"plantId"`
	CareRegimenID string `json:"careRegimenId"`
	Nickname      string `json:"nickname"`
	Location      string `json:"location"`
}

type NewPlant struct {
	CommonName      string `json:"commonName"`
	BotanicalName   string `json:"botanicalName"`
	WaterPreference string `json:"waterPreference"`
	SunPreference   string `json:"sunPreference"`
	SoilPreference  string `json:"soilPreference"`
}

type NewWatering struct {
	PlantBabyID string `json:"plantBabyID"`
	Amountml    int    `json:"amountml"`
	WateredOn   string `json:"wateredOn"`
}

type Plant struct {
	ID              string `json:"id"`
	CommonName      string `json:"commonName"`
	BotanicalName   string `json:"botanicalName"`
	WaterPreference string `json:"waterPreference"`
	SunPreference   string `json:"sunPreference"`
	SoilPreference  string `json:"soilPreference"`
}

type PlantBaby struct {
	ID          string       `json:"id"`
	Plant       *Plant       `json:"plant"`
	OwnerID     string       `json:"ownerID"`
	CareRegimen *CareRegimen `json:"careRegimen"`
	Location    string       `json:"location"`
	Nickname    string       `json:"nickname"`
	AddedOn     string       `json:"addedOn"`
}

type RefreshToken struct {
	Token string `json:"token"`
}

type Watering struct {
	ID          string `json:"id"`
	WateredOn   string `json:"wateredOn"`
	Amountml    int    `json:"amountml"`
	PlantBabyID string `json:"plantBabyID"`
}
