// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CareRegimen struct {
	ID      string `json:"id"`
	Waterml int    `json:"waterml"`
	Waterhr int    `json:"waterhr"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Member struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	CreatedOn string `json:"createdOn"`
}

type NewMember struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewNurseryAddition struct {
	Plant string `json:"plant"`
}

type NewPlant struct {
	CommonName      string `json:"commonName"`
	BotanicalName   string `json:"botanicalName"`
	WaterPreference string `json:"waterPreference"`
	SunPreference   string `json:"sunPreference"`
	SoilPreference  string `json:"soilPreference"`
}

type Plant struct {
	ID              string `json:"id"`
	CommonName      string `json:"commonName"`
	BotanicalName   string `json:"botanicalName"`
	WaterPreference string `json:"waterPreference"`
	SunPreference   string `json:"sunPreference"`
	SoilPreference  string `json:"soilPreference"`
}

type PlantBaby struct {
	ID          string       `json:"id"`
	Owner       *Member      `json:"owner"`
	Plant       *Plant       `json:"plant"`
	CareRegimen *CareRegimen `json:"careRegimen"`
}

type RefreshToken struct {
	Token string `json:"token"`
}
